name: LandClaim
main: net.minespire.landclaim.LandClaim
version: 1.0
depend: [Vault, WorldGuard, WorldEdit]
api-version: 1.13
permissions:
  landclaim.*:
    default: op
    description: All WGLandClaim permissions (no restrictions or charges).
    children:
      landclaim.claimplot: true
      landclaim.bypass: true
  landclaim.claimplot:
    description: Ability to claim a WGLandClaim plot and get charged
    default: true
  landclaim.claimregion:
    description: Ability to claim a WGLandClaim region and get charged
    default: false
  landclaim.bypass.*:
    description: Bypasses costs and limits on WGLandClaim regions, plots, and flags
    default: false
    children:
      landclaim.bypass.claim: true
      landclaim.bypass.claimplot: true
      landclaim.bypass.flags: true
  landclaim.bypass.claim:
    description: Bypass cost and limits of region claiming.
    default: false
  landclaim.bypass.claimplot:
    description: Bypass cost and limits of plot claiming.
    default: false
  landclaim.bypass.flags:
    description: Bypass costs of setting flags.
    default: false
  landclaim.regions.*:
    description: Can have unlimited number of claims
    default: false
  landclaim.plots.*:
    description: Can have unlimited number of plots
    default: false
commands:
  lc:
    description: Base command for land claim
    usage: Type /lc claim <regionName> or /lc claimplot <plotName>
  lc list:
    description: Base command for land claim
    usage: Type /lc claim <regionName> or /lc claimplot <plotName>