name: LandClaim
main: net.minespire.landclaim.LandClaim
version: 1.0
depend: [Vault, WorldGuard, WorldEdit]
api-version: 1.13
permissions:
  landclaim.*:
    default: op
    description: All WGLandClaim permissions (no restrictions or charges).
    children:
      landclaim.claimplot: true
      landclaim.bypass: true
  landclaim.reload:
    description: Ability to reload LandClaim
    default: false
  landclaim.list:
    description: List your regions and plots
    default: true
  landclaim.claimplot:
    description: Ability to claim a WGLandClaim plot and get charged
    default: true
  landclaim.claimregion:
    description: Ability to claim a WGLandClaim region and get charged
    default: true
  landclaim.regions.*:
    description: Can have unlimited number of claims
    default: false
  landclaim.plots.*:
    description: Can have unlimited number of plots
    default: false
  landclaim.world.*:
    description: Can claim in any world
    default: false
commands:
  lc:
    description: Base command for land claim
    usage: Type /lc claim <regionName> or /lc claimplot <plotName>