Version: 1.0.0 # Do not change this
  
Claims:
  Regions:
    MinSize: 500           # In square blocks (lenth x width).
    MaxSize: 10000
    MaxLWRatio: 4          # This determines the maximum ratio of the longest side to the shortest. Example 400 blocks x 100 blocks = 4. This prevents impractically shaped regions.
    PricePerBlock: 1.5     # Area x PricePerBlock = RegionCost
    MaxClaims: 3           # You can bypass this with the permission landclaim.regions.# (landclaim.claims.5 for example)
  Plots:
    PricePerBlock: 0.1     # Volume x PricePerBlock = PlotCost
    BaseCost: 500          # The lowest price for a plot no matter how small.
    MaxPlotsTotal: 3       # Max plots a single player can have overall. Bypass with landclaim.plots.# (landclaim.plotstotal.5 for example)
LandAssetSystem:
  Tax:
    Enabled: true
    Amount: 1.6            # Percent to tax each [Frequency] unit of time. Tax levied on valuable land
    Frequency: '1 day'     # with bad upkeep will be worth it to sell, because passive income will be lower than the tax
  LandValue:
    Appreciation: 
      Frequency: '1 day'
    Depreciation:
      Something:
    PassiveIncome:
      Enabled: true
      Amount: 1.6          # Percent to award land owner each [Frequency] unit of time.
      Frequency: '1 day'
      UpkeepDifficulty: 3       # 1 = very easy, 2 = easy, 3 = medium, 4 = hard, 5 = very hard
                                # Upkeep is a core aspect of land value and income. A hidden upkeep modifier
                                # can vary between 0 and 1 and can make a piece of land either more
                                # worth it to hold on to for passive income or more worth it to sell

    
    
GUI:
  Slots: 27
  FillerItem: GLASS_PANE
  ClaimRegion:
    Title: '        &3Confirm Region Claim'
    ClaimItem:
      Material: GRASS_BLOCK
      Slot: 14
      ItemName: 'Are You Sure You Want To Claim This Region?'
      Lore: '&5Region Name: &f{RegionName}|&5Region Cost: &f{RegionCost}|&5Region Size: &f{RegionLength} x {RegionWidth}|&aClick to confirm purchase.'# Separate lore into new lines with the pipe symbol (|).
  ClaimPlot:
    Title: '        &3Confirm Plot Claim'
    ClaimItem:
      Material: DIRT
      Slot: 14
      ItemName: 'Are You Sure You Want To Claim This Plot?'
      Lore: '&5Region Name: &f{RegionName}|&5Region Cost: &f{RegionCost}|&5Region Size: &f{RegionLength} x {RegionHeight} x {RegionWidth}|&aClick to confirm purchase.'
  ClaimsList:
    Title: '      &3Your Regions and Plots'
    OwnerRegions:
      Material: DIAMOND_BLOCK
      ItemName: '&3Regions You Own'
      Slot: 11
    MemberRegions:
      Material: DIAMOND_ORE
      ItemName: '&3Regions You Are a Member Of'
      Slot: 13
    OwnerPlots:
      Material: EMERALD_BLOCK
      ItemName: '&3Plots You Own'
      Slot: 15
    MemberPlots:
      Material: EMERALD_ORE
      ItemName: '&3Plots You Are a Member Of'
      Slot: 17